language: c
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install gperf; fi
# FIXME: add an install target, for the love of God!
script: git submodule init && git submodule update && make

